name: 機能追加
description: このプロジェクトのアイデアを提案する
labels: 
  - enhancement

body:
  - type: textarea
    id: feature_description
    attributes:
      label: 機能詳細
      description: 追加したい機能についての説明を入力してください。

  - type: textarea
    id: feature_notes
    attributes:
      label: 備考

  - type: textarea
    id: tasks
    attributes:
      label: タスク
      description: |
        必要なタスクを記載してください。
        例:
        ```
        - [ ] コーディング
        - [ ] コードレビュー
        - [ ] ユニットテスト
        - [ ] PR
        ```
