name: 機能改善、パフォーマンス向上
description: 機能の改善、パフォーマンスの向上等の、バグや新機能以外の修正案はこちら

body:
  - type: textarea
    id: improvement_description
    attributes:
      label: 改善内容
      description: 改善したい機能の詳細を入力してください。

  - type: textarea
    id: how_to_improve
    attributes:
      label: 改善方法
      description: 改善方法について入力してください。

  - type: textarea
    id: feature_notes
    attributes:
      label: 備考
