name: Tests

on:
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  id-token: none
  issues: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        node-version: ['20']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.14.1
      - run: pnpm install

      - name: Check Lint
        run: pnpm run lint:ci
      
      - name: Code Formatting Check
        run: pnpm run format:ci
      
      - name: Build Check
        run: pnpm run build
